### ISSUE TITLE
Announcement Funnel

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/IT#132]
Currently there is no centralized process to move information into the various SCRF 'announcement' spaces. 

Announcement requests will be made via submitting an issue template. The created issue will then be tracked through a GitHub Project Board so that it can be properly reviewed. This centralized approach will make it easier for SCRF to bring announcements forward to wider marketing. 

Root Issue: [Community Routines Development](https://github.com/smartcontractresearchforum/engagement/issues/175)

## TODOs

- [x] Issue template created  -- https://github.com/smartcontractresearchforum/discovery/issues/new/choose
- [x] Project Board setup -- going to route to Discovery - https://github.com/orgs/smartcontractresearchforum/projects/41
- [x] End Points integrated

## Issue Template
Standardize what information is needed and what steps need to be completed before the announcement can go live.
- date to release announcement
- title
- urls
- body of announcement
- teams / roles to tag

## Project Board
Announcements are sourced in this silo. Used by the SCRF team to ensure that all announcements are singularly sourced. 

Capture process and review to ensure all announcements are vetted. Copy check before approval of release by @marvino3  

## End Points
- Discord
- Discourse
- Socials @MichaelSCRF 
- Community Calls

## Cross Pollination w/Discovery
@smartcontractresearchforum/discovery
How can announcement best interface with socials funnel?
@marvino3

**Comment by marvino3** [comment]
@SirAh0 we already use the [Disco Promo board](https://github.com/orgs/smartcontractresearchforum/projects/41) to capture ideas that people want promoted or announced across the org. Right now, the promo is external. Do we want to repurpose this board so that we are capturing all info to be announced in one board? And people can label if they think the announcement should be internal, external, both

**Comment by SirAh0** [comment]
Sounds good I'll route announcements to the [Disco Promo board](https://github.com/orgs/smartcontractresearchforum/projects/41)

**Comment by SirAh0** [comment]
Everything is setup and ready to be used.
