### ISSUE TITLE
Analytics Guild - Nov 2022

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/IT#143]
# Agenda

Review the numbers and open discussion.

# Resources

Presentation Google Slide - [Analytics Guild Report November 2022](https://docs.google.com/presentation/d/1k-280DrxBfhOWhNaPAOHStUjtsSYwoP4Jz0FA-wULxE/edit?usp=sharing)

Analytics Guild - Project Proposal - [Google Doc](https://docs.google.com/presentation/d/1kMdIumokqO0m5jV4kCWe7CI_FJ0O0me2pS5ry9PsYyE/edit?usp=sharing)

[Meet Recording](https://drive.google.com/file/d/1B14gFTyCR4JGvbj6B0NBXAdTjz-NMm3i/view?usp=sharing)

[October Analytics Guild 2022](https://github.com/smartcontractresearchforum/IT/issues/125)

[All Guild Meet Notes](https://github.com/orgs/smartcontractresearchforum/projects/34/views/11) on the [IT Help Desk Project Board](https://github.com/orgs/smartcontractresearchforum/projects/34/views/10).

# TODOs
- [ ] Don't forget to record
- [x] fill out this issue
- [ ] Fold in YouTube Metrics

**Comment by SirAh0** [comment]
Should this guild stay public or private?
- driving data for year end reports
- get relevant info out, without too much details

**Comment by SirAh0** [comment]
Discourse native metrics

**Comment by SirAh0** [comment]
next meeting what is the point of this meeting? lets have a discussion about it.
