### ISSUE TITLE
Forum Banner - Notification Update

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/IT#146]
# TODO
- [ ] Generate read only global API key with specific access to notification category @eleventh19 @SirAh0 
- [ ] Create private category
- [ ] Assign SCRF role to that category (post)
- [ ] update banner code to display most recent post from that category using API key
- [ ] Create process document on how to use notification banner feature

**Comment by SirAh0** [comment]
**Discourse Native Banner Notification**
A topic can be globally pinned and displayed on the top of every page. The section can be closed (dismissed) by the user. See screenshot below of it's default look and placement.

![image](https://user-images.githubusercontent.com/12703396/202345818-dfafc3c1-ca1f-451c-8bad-85246ab45da6.png)
