### ISSUE TITLE
GA Tracking Codes Funnel

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/IT#151]
- [ ] Create a new issue form to request a custom tracking code
- [ ] add a new label for these issue types
- [ ] add a new view to the IT Help Desk pb

@zubepaul
