### ISSUE TITLE
SourceCred Guild Agenda - November 2022

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/IT#153]
# Agenda

- Month to Month Payout Model
- Node / Edge weights adjustment to promote new content 
- custom trust level / badges affect cred flow?
    - designated researcher flagging comment will boost the OP
- ending the free lunch
    - divert to promote content creation\
- presentation of analytics

# Resources

🔗[Presentation Deck](https://docs.google.com/presentation/d/1QfrF5OtAChGCGSAMDW-uaNJzc0pB6vwiQMdPZiXfXBc/edit?usp=sharing)

🔗 [November Agenda](https://github.com/smartcontractresearchforum/IT/issues/144)

🔗 [Meet Recording]() - coming soon

# TODOs
- [ ] Don't forget to record!
- [ ] Update SCRF SCRED Doc.
- [ ] Add recording link to above resource
