### ISSUE TITLE
Analytics Guild - Dec 2022 

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/IT#154]
# Agenda

Review the numbers and open discussion.

# Resources

Presentation Google Slide - [Analytics Guild Report December 2022](https://docs.google.com/presentation/d/1zR__ffZ7ZrDoDwU5mmrM1zb0YtQ0k0pUjgb8jcqzV2Y/edit#slide=id.g1522a9bc93b_0_49)

Analytics Guild - Project Proposal - [Google Doc](https://docs.google.com/presentation/d/1kMdIumokqO0m5jV4kCWe7CI_FJ0O0me2pS5ry9PsYyE/edit?usp=sharing)

[Meet Recording]() - coming soon

[November Analytics Guild 2022](https://github.com/smartcontractresearchforum/IT/issues/143)

[All Guild Meet Notes](https://github.com/orgs/smartcontractresearchforum/projects/34/views/11) on the [IT Help Desk Project Board](https://github.com/orgs/smartcontractresearchforum/projects/34/views/10).

# TODOs
- [ ] Don't forget to record
- [ ] fill out this issue
- [ ] Fold in YouTube Metrics

**Comment by SirAh0** [comment]
**Actionable**
@zubepaul  @MichaelSCRF 
reach and impact promotion via sharing, valuable message


Direct outreach to people who have valuable contributions to the forum. encouraging- we are paying attention to those recognitions. 

Roll information into a quick report in the community call

**Comment by Coinproz** [comment]
we should attempt to formalize a qualitative survey of community participants to understand why they decided to become scrf advocates and take scrf posts to other platforms.

should start with ulysses and freakytainment due to the high traffic to their profiles

**Comment by SirAh0** [comment]
analytics provide insight to good content we can select for a curation view on the new homepage of scrf for example.

**Comment by Coinproz** [comment]
potential to integrate viewing/interaction with other elements of the community directly from the splash page

**Comment by Coinproz** [comment]
some of the comments on the forum have become recursive and redundant.  it might be useful to adjust the gradation of sourcecred payout scale so that it takes a higher score to start getting a higher payout. furthermore, it might be useful for moderators to upvote comments with questions so that people who ask questions get paid a higher payout than those who make comments without asking a question. There seems to be an understanding of how to make AI assisted comments to game the system to get paid for doing very little; so in this context it might be helpful to start attempting to change behavior through adjustments to sourcecred allocation and how allocations are decided.

**Comment by SirAh0** [comment]
**Adjacent Discord Servers**
Other servers following SCRF has been flat over the past 30 days. How can we increase outreach to SCRF adjacent discord servers.
